import './style.css';
import './current.css';
import {directions,imageFor} from './data.js';
import {locale,pick,t,changeLocale} from './copy.js';

const root=document.querySelector('#review'),params=new URLSearchParams(location.search),ids=new Set(directions.map(d=>d.id));
const valid=s=>[...new Set((s||'').split(',').filter(x=>ids.has(x)))];
let favorites=valid(params.get('liked')),comparison=valid(params.get('pick')).slice(0,2),filter='all',notes='',detail=null,tab='image',sampleState='normal',sampleRunning=false;
const paths={heart:'<path d="M20.8 4.6a5.5 5.5 0 0 0-7.8 0L12 5.7l-1.1-1.1a5.5 5.5 0 0 0-7.8 7.8L12 21l8.8-8.6a5.5 5.5 0 0 0 0-7.8Z"/>',close:'<path d="m6 6 12 12M6 18 18 6"/>',plus:'<path d="M12 5v14M5 12h14"/>',gear:'<path d="m9 3-1 3-3 1v3l-2 2 2 2v3l3 1 1 3h6l1-3 3-1v-3l2-2-2-2V7l-3-1-1-3Z"/><circle cx="12" cy="12" r="3"/>',refresh:'<path d="M3 10a9 9 0 0 1 15-6l3 3M21 3v4h-4M21 14a9 9 0 0 1-15 6l-3-3M3 21v-4h4"/>',check:'<path d="m5 12 4 4L19 6"/>',compare:'<rect x="3" y="4" width="7" height="16" rx="1"/><rect x="14" y="4" width="7" height="16" rx="1"/>',expand:'<path d="M8 3H3v5M16 3h5v5M3 16v5h5M21 16v5h-5"/>',copy:'<rect x="8" y="8" width="12" height="13" rx="2"/><path d="M15 8V3H3v12h5"/>',download:'<path d="M12 3v12m-5-5 5 5 5-5M4 16v5h16v-5"/>'};
const icon=n=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${paths[n]||''}</svg>`;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const get=id=>directions.find(d=>d.id===id);
const name=d=>`${d.letter} ${pick(d.name)}`;
function syncUrl(){const u=new URL(location.href);for(const[k,a]of[['liked',favorites],['pick',comparison]]){if(a.length)u.searchParams.set(k,a.join(','));else u.searchParams.delete(k);}u.searchParams.set('lang',locale);history.replaceState(null,'',u);}
function status(message){const el=document.querySelector('dialog[open] .ar__status')||document.querySelector('.ar__status');el.textContent=message;el.classList.add('ar__status--visible');clearTimeout(status.timer);status.timer=setTimeout(()=>el.classList.remove('ar__status--visible'),2600);}
function controls(d){return `<div class="ar__card-actions"><button data-action="favorite" data-id="${d.id}" aria-pressed="${favorites.includes(d.id)}">${icon('heart')}<span>${t(favorites.includes(d.id)?'favorited':'favorite')}</span></button><button data-action="compare" data-id="${d.id}" aria-pressed="${comparison.includes(d.id)}">${icon(comparison.includes(d.id)?'check':'compare')}<span>${t(comparison.includes(d.id)?'comparing':'compare')}</span></button></div>`;}
function artwork(d,eager=false){return `<div class="ar__artwork" data-art="${d.id}"><img src="${imageFor(d.id)}" alt="${esc(name(d)+t('imageAlt'))}" width="1024" height="1536" loading="${eager?'eager':'lazy'}" decoding="async" draggable="false"><div class="ar__image-error" hidden><p>${t('imageError')}</p><button data-action="retry-image" data-id="${d.id}">${t('retry')}</button></div></div>`;}
function card(d,i){return `<article class="ar__card" data-direction="${d.id}"><div class="ar__card-head"><div><h2><span class="ar__letter">${d.letter}</span>${pick(d.name)}</h2><p>${pick(d.line)}</p></div><span class="ar__swatches" aria-hidden="true">${d.palette.slice(1,5).map(c=>`<i style="background:${c}"></i>`).join('')}</span></div><div class="ar__picture">${artwork(d,i===0)}<button class="ar__inspect" data-action="inspect" data-id="${d.id}" aria-label="${esc(t('view')+' '+name(d))}"><span class="ar__inspect-label">${icon('expand')}${t('view')}</span></button></div><div class="ar__card-meta"><span>${pick(d.tags).join(' / ')}</span><span>${d.en}</span></div>${controls(d)}</article>`;}
function render(){
 const focused=document.activeElement?.dataset,focusAction=focused?.action,focusId=focused?.id;
 document.body.classList.remove('ar--modal');
 document.documentElement.lang=locale==='zh'?'zh-CN':'en';document.title=t('title');
 const shown=filter==='all'?directions:directions.filter(d=>favorites.includes(d.id));
 root.innerHTML=`<div class="ar"><header class="ar__header"><a class="ar__brand" href="../" target="_blank" rel="noopener"><span class="ar__mark" aria-hidden="true"><i></i><i></i><i></i><i></i></span>${t('title')}</a><nav><a class="ar__game-link" href="../" target="_blank" rel="noopener">${t('backGame')}</a><button data-action="language">${t('tabLang')}</button></nav></header><aside class="ar__current-review"><p>${t('archiveNotice')}</p><a href="../pixel-lab/?lang=${locale}&section=experiments">${t('currentReview')}</a></aside><section class="ar__intro"><div><h1>${t('heading').split('\n').join('<br>')}</h1></div><div class="ar__intro-copy"><p>${t('intro')}</p><span class="ar__scope">${t('scope')}</span></div></section><div class="ar__toolbar"><div role="group" aria-label="${t('all')}"><button data-action="filter-all" aria-pressed="${filter==='all'}">${t('all')} <span>6</span></button><button data-action="filter-liked" aria-pressed="${filter==='liked'}">${icon('heart')}${t('liked')} <span>${favorites.length}</span></button></div><small>${t('layoutNote')}</small></div><section class="ar__gallery" aria-label="${t('all')}">${shown.length?shown.map(card).join(''):`<div class="ar__empty"><p>${t('empty')}</p><button data-action="filter-all">${t('returnAll')}</button></div>`}</section><section class="ar__feedback"><div><h2>${t('feedbackTitle')}</h2><p>${t('feedbackIntro')}</p><div class="ar__chosen">${favorites.length?favorites.map(id=>`<span>${esc(name(get(id)))}</span>`).join(''):`<small>${t('pinHint')}</small>`}</div></div><div><label for="review-notes">${t('notesLabel')}</label><textarea id="review-notes" rows="4" maxlength="4000" placeholder="${esc(t('notesPlaceholder'))}"></textarea><div class="ar__feedback-actions"><button class="ar__solid" data-action="copy">${icon('copy')}${t('copy')}</button><button data-action="download">${icon('download')}${t('download')}</button></div><small>${t('privacy')}</small></div></section><footer class="ar__footer">${t('reviewFooter')}<span>2026.09 · v0.5</span></footer></div><div class="ar__dock"><div class="ar__dock-picks">${comparison.length?comparison.map(id=>`<button data-action="compare" data-id="${id}" aria-label="${esc(t('compareRemoved')+' '+name(get(id)))}"><b>${get(id).letter}</b><span>${pick(get(id).name)}</span>${icon('close')}</button>`).join(''):`<span>${icon('compare')}${t('compareHint')}</span>`}</div><button class="ar__solid" data-action="open-compare" ${comparison.length!==2?'disabled':''}>${t('compareNow')} <span>${comparison.length}/2</span></button></div><div class="ar__status" role="status" aria-live="polite"></div><dialog class="ar__dialog" aria-label="${t('view')}"></dialog>`;
 document.querySelector('#review-notes').value=notes;
 wireImages(root);
 if(focusAction)root.querySelector(`[data-action="${CSS.escape(focusAction)}"]${focusId?`[data-id="${CSS.escape(focusId)}"]`:''}`)?.focus({preventScroll:true});
 const dialog=document.querySelector('dialog');dialog.addEventListener('click',e=>{if(e.target===dialog)closeDialog();});dialog.addEventListener('cancel',()=>{detail=null;document.body.classList.remove('ar--modal');});dialog.addEventListener('close',()=>document.body.classList.remove('ar--modal'));
}
function wireImages(parent){for(const img of parent.querySelectorAll('img')){const fail=()=>{img.closest('.ar__artwork').classList.add('ar__artwork--failed');img.closest('.ar__artwork').querySelector('.ar__image-error').hidden=false;};img.addEventListener('error',fail);img.addEventListener('load',()=>{img.closest('.ar__artwork').classList.remove('ar__artwork--failed');img.closest('.ar__artwork').querySelector('.ar__image-error').hidden=true;});if(img.complete&&!img.naturalWidth)fail();}}
function closeDialog(){document.querySelector('dialog').close();detail=null;}
function openDetail(id,keep=false){const focusAction=keep?document.activeElement?.dataset.action:null;detail=id;const d=get(id),dialog=document.querySelector('dialog');if(!keep){tab='image';sampleState='normal';sampleRunning=false;}
 dialog.className='ar__dialog';dialog.innerHTML=`<div class="ar__modal-header"><h2><span class="ar__letter">${d.letter}</span>${pick(d.name)}</h2><button class="ar__icon" data-action="close" aria-label="${t('close')}">${icon('close')}</button></div><div class="ar__detail"><div class="ar__detail-visual"><div class="ar__tabs" role="group" aria-label="${t('view')}"><button data-action="tab-image" aria-pressed="${tab==='image'}">${t('image')}</button><button data-action="tab-components" aria-pressed="${tab==='components'}">${t('components')}</button></div>${tab==='image'?artwork(d,true):sample(d)}<p class="ar__disclaimer">${t(tab==='image'?'conceptNote':'sampleNote')}</p></div><aside class="ar__detail-copy"><p class="ar__thesis">${pick(d.mood)}</p>${[['art','shape'],['interface','ui'],['moment','moment'],['risk','risk'],['cost','cost']].map(([k,v])=>`<section><h3>${t(k)}</h3><p>${pick(d[v])}</p></section>`).join('')}<div class="ar__question"><h3>${t('question')}</h3><p>${pick(d.question)}</p></div>${controls(d)}</aside></div>`;wireImages(dialog);dialog.insertAdjacentHTML('beforeend','<div class="ar__status" role="status" aria-live="polite"></div>');if(!dialog.open)dialog.showModal();document.body.classList.add('ar--modal');
 if(focusAction)(dialog.querySelector(`[data-action="${CSS.escape(focusAction)}"]`)||dialog.querySelector('[data-action="sample-play"]'))?.focus({preventScroll:true});
}
function sample(d){if(d.id==='pixel')return `<div class="ar__current-review"><p>${t('pixelMoved')}</p><a href="../pixel-lab/?lang=${locale}&section=components">${t('currentReview')}</a></div>`;return `<div class="ar__sample-switch" role="group" aria-label="${t('components')}">${['normal','selected','upgrade'].map(s=>`<button data-action="sample-${s}" aria-pressed="${sampleState===s}">${t(s)}</button>`).join('')}</div><section class="ar__sample ar__sample--${d.id}" aria-label="${esc(name(d)+t('uiAlt'))}"><header><strong>${t('gameName')}</strong><span>${icon('gear')}5</span></header><div class="ar__sample-hud"><span>${icon('heart')}100</span><span>4 / 8</span></div><div class="ar__sample-board" data-state="${sampleState}">${Array.from({length:12},(_,i)=>`<i class="${sampleState==='selected'&&[5,6].includes(i)?'ar__tile--selected':''}">${i===5?icon('gear'):i===6?icon('plus'):''}</i>`).join('')}</div>${sampleState==='upgrade'?`<button class="ar__upgrade" data-action="sample-choose"><span class="ar__bubble-symbol" aria-hidden="true"><i></i><i></i><i></i></span><span><strong>${t('bubble')}</strong><small>${t('bubbleDesc')}</small></span>${icon('plus')}</button>`:''}<div class="ar__sample-actions"><button data-action="sample-play" class="ar__sample-primary">${t(sampleRunning?'reset':sampleState==='upgrade'?'choose':'start')}</button><button data-action="sample-refresh" ${sampleRunning?'disabled':''}>${icon('refresh')}${t('refresh')}</button></div><div class="ar__sample-progress"><span></span></div><p class="ar__sample-state">${t(sampleRunning?'running':sampleState)}</p></section>`;}
function openCompare(){if(comparison.length!==2)return;detail='compare';const dialog=document.querySelector('dialog');dialog.className='ar__dialog ar__dialog--compare';dialog.innerHTML=`<div class="ar__modal-header"><h2>${t('compareNow')}</h2><button class="ar__icon" data-action="close" aria-label="${t('close')}">${icon('close')}</button></div><div class="ar__compare-grid">${comparison.map((id,i)=>{const d=get(id);return `<section><label class="ar__select-label" for="compare-${i}">${t(i?'right':'left')}</label><select id="compare-${i}" data-compare-index="${i}">${directions.map(x=>`<option value="${x.id}" ${x.id===id?'selected':''}>${esc(name(x))}</option>`).join('')}</select>${artwork(d,true)}<button class="ar__inspect-single" data-action="inspect" data-id="${id}">${icon('expand')}${t('inspectOne')}</button><h3>${pick(d.line)}</h3><p>${pick(d.ui)}</p><small>${pick(d.risk)}</small></section>`;}).join('')}</div><p class="ar__disclaimer">${t('conceptNote')}</p>`;wireImages(dialog);if(!dialog.open)dialog.showModal();document.body.classList.add('ar--modal');}
function summary(){return `${t('title')}\n${new Date().toLocaleDateString(locale==='zh'?'zh-CN':'en')}\n\n${t('shortlistTitle')}: ${favorites.length?favorites.map(id=>name(get(id))).join(' / '):t('none')}\n${t('compareNow')}: ${comparison.length?comparison.map(id=>name(get(id))).join(' / '):t('none')}\n\n${t('notesTitle')}\n${notes.trim()||t('none')}\n\n${location.href}\n${t('scope')}\n`;}
function download(){const url=URL.createObjectURL(new Blob([summary()],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='toy-workshop-art-review.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);status(t('downloaded'));}
root.addEventListener('input',e=>{if(e.target.id==='review-notes')notes=e.target.value;});
root.addEventListener('change',e=>{if(e.target.dataset.compareIndex!==undefined){const i=Number(e.target.dataset.compareIndex),other=1-i,old=comparison[i];comparison[i]=e.target.value;if(comparison[other]===e.target.value)comparison[other]=old;syncUrl();render();openCompare();}});
root.addEventListener('click',async e=>{
 const b=e.target.closest('button[data-action]');if(!b||b.disabled)return;const a=b.dataset.action,id=b.dataset.id;
 if(a==='inspect')openDetail(id);
 else if(a==='close')closeDialog();
 else if(a==='language'){changeLocale();syncUrl();render();}
 else if(a.startsWith('filter-')){filter=a==='filter-all'?'all':'liked';render();}
 else if(a==='favorite'||a==='compare'){
  const list=a==='favorite'?favorites:comparison,at=list.indexOf(id),wasOpen=detail,oldTab=tab;
  if(at>=0)list.splice(at,1);else if(a==='compare'&&list.length===2){status(t('maxTwo'));return;}else list.push(id);
  syncUrl();render();if(wasOpen&&wasOpen!=='compare'){tab=oldTab;openDetail(wasOpen,true);}else if(wasOpen==='compare'&&comparison.length===2)openCompare();
  status(t(a==='favorite'?(at>=0?'favRemoved':'favAdded'):(at>=0?'compareRemoved':'compareAdded')));
 }else if(a==='open-compare')openCompare();
 else if(a==='tab-image'||a==='tab-components'){tab=a.slice(4);openDetail(detail,true);}
 else if(a.startsWith('sample-')){
  if(['sample-normal','sample-selected','sample-upgrade'].includes(a)){sampleState=a.slice(7);sampleRunning=false;}
  else if(a==='sample-play'&&sampleState!=='upgrade')sampleRunning=!sampleRunning;
  else if(a==='sample-choose'||a==='sample-play'){sampleState='selected';sampleRunning=false;}
  else if(a==='sample-refresh'){sampleState='selected';}
  openDetail(detail,true);status(t(a==='sample-choose'?'sampleUpgrade':'sampleFeedback'));
 }else if(a==='retry-image'){const box=b.closest('.ar__artwork'),img=box.querySelector('img');box.classList.remove('ar__artwork--failed');box.querySelector('.ar__image-error').hidden=true;img.src=imageFor(id);}
 else if(a==='download')download();
 else if(a==='copy'){b.disabled=true;try{if(!navigator.clipboard)throw new Error('unavailable');await navigator.clipboard.writeText(summary());status(t('copied'));}catch{status(t('copyFailed'));}finally{b.disabled=false;}}
});
render();
