import {createRequire} from 'node:module';
import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
const {chromium}=createRequire('/Users/yin/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/package.json')('playwright');
const base=process.env.QA_BASE||'http://127.0.0.1:5193/',phase=process.env.QA_PASS||'after',out=`_qa/compact-r24/${phase}`;await fs.mkdir(out,{recursive:true});const browser=await chromium.launch(),results=[];
try{for(const [width,height]of [[320,568],[390,600],[390,844],[440,600],[1280,720]]){
 const ctx=await browser.newContext({viewport:{width,height},hasTouch:true,isMobile:width<700}),p=await ctx.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.clock.install();await p.goto(base+'?lang='+(width===320?'en':'zh'));await p.locator('.tw[data-renderer=pixel]').waitFor({timeout:60000});const step=n=>p.clock.runFor(n),act=async a=>{await p.locator(`[data-action="${a}"]`).tap();await step(300);};await step(800);await p.screenshot({path:`${out}/${width}x${height}-teaching.png`});
 await act('pause');await act('levels');await act('level-0');await act('confirm');await step(500);
 const metrics=await p.evaluate(()=>{const r=e=>{const b=e.getBoundingClientRect();return{x:b.x,y:b.y,w:b.width,h:b.height,bottom:b.bottom,right:b.right};};return{game:r(document.querySelector('.tw')),footer:r(document.querySelector('.tw__footer')),bench:r(document.querySelector('#supply')),toggle:r(document.querySelector('[data-action=bench-toggle]')),scroll:document.documentElement.scrollHeight,viewport:visualViewport.height,bodyWidth:document.documentElement.scrollWidth,hudZ:getComputedStyle(document.querySelector('.tw__hud')).zIndex,fieldZ:getComputedStyle(document.querySelector('.tw__field')).zIndex,targets:[...document.querySelectorAll('button')].filter(e=>e.offsetWidth&&e.offsetHeight&&getComputedStyle(e).visibility!=='hidden'&&!e.closest('[hidden]')).map(e=>({id:e.dataset.action||e.dataset.cell||e.dataset.source,...r(e)}))};});
 if(phase!=='before'){assert(metrics.scroll<=height+1,JSON.stringify(metrics));assert(metrics.footer.bottom<=height-7);assert(metrics.bodyWidth<=width);assert(metrics.toggle.w>=52&&metrics.toggle.h>=58);assert(metrics.toggle.right<=metrics.game.right+.5);assert(+metrics.fieldZ>+metrics.hudZ);assert.deepEqual(metrics.targets.filter(b=>b.w<43.5||b.h<43.5),[]);}
 await p.screenshot({path:`${out}/${width}x${height}-ready.png`});await act('bench-toggle');await p.screenshot({path:`${out}/${width}x${height}-land.png`});await p.locator('[data-source=land]').tap();await p.locator('[data-cell="0,3"]').tap();await step(300);assert.equal(await p.locator('.tw').getAttribute('data-cells'),'14');
 await act('main');await step(1800);await p.screenshot({path:`${out}/${width}x${height}-enemy.png`});await act('pause');await p.screenshot({path:`${out}/${width}x${height}-pause.png`});assert(await p.locator('[data-action=resume]').isVisible());await act('resume');assert.deepEqual(errors,[]);results.push({width,height,metrics,errors});await ctx.close();
}}finally{await browser.close();}await fs.writeFile(`${out}/checks.json`,JSON.stringify(results,null,2));console.log(results.map(({width,height,metrics})=>({width,height,gameHeight:metrics.game.h,scroll:metrics.scroll,footer:metrics.footer.bottom,toggle:metrics.toggle.w})));
