import test from 'node:test';
import assert from 'node:assert/strict';
import {Workshop,occupied,pointAt,LENGTH,SimulationClock} from '../src/engine.js';
const run=(g,n=2000)=>{for(let i=0;i<n;i++){if(g.choices.length)g.chooseUpgrade(0);else g.tick(1/60);}};
const fresh=()=>{const g=new Workshop();g.reset('run');return g;};
test('depleted upgrade pools stay unique and rewards are consumed once',()=>{
 for(const hp of [100,80]){
  const g=fresh();g.units=[];g.hp=hp;g.xp=6;g.offerUpgrades();
  assert.equal(g.choices.length,hp===100?1:2);
  assert.equal(new Set(g.choices).size,g.choices.length);
  assert.ok(g.choices.includes('supplies'));
  assert.equal(g.choices.includes('repair'),hp<100);
  assert.ok(g.chooseUpgrade(g.choices.indexOf('supplies')));
  assert.equal(g.coins,5);assert.equal(g.chooseUpgrade(0),false);assert.equal(g.coins,5);
 }
});
test('exhausted permanent upgrades never get padded with duplicate supplies',()=>{
 const g=fresh();g.units=[];g.add('spring',1,0,0);g.buffs=['spring-speed','spring-bounce'];g.xp=160;
 for(let i=0;i<6;i++){g.offerUpgrades();assert.deepEqual(g.choices,['supplies']);assert.ok(g.chooseUpgrade(0));}
 assert.equal(g.coins,30);assert.equal(g.upgradeLevel,6);assert.deepEqual(g.choices,[]);
});
function tutorial(direct=true){const g=new Workshop();g.place('tray',1,2);run(g,300);assert.equal(g.stage,'second');if(!direct)g.place('tray',2,2);const p=g.place(direct?'tray':g.units[1].id,1,2);assert.ok(p.ok);assert.equal(p.freed,direct?0:2);assert.equal(g.stage,'expand');g.expand();g.place('tray',1,4);return g;}
test('direct tray and board merge finish the same tutorial without XP',()=>{for(const direct of[true,false]){const g=tutorial(direct);assert.equal(g.stage,'ready');assert.equal(g.xp,0);assert.equal(g.coins,0);assert.deepEqual(g.lineup(),fresh().lineup());}});
test('invalid footprints and wrong rank/kind are atomic with exact mismatch',()=>{const g=fresh(),before=JSON.stringify(g);assert.equal(g.place('reserve:2',5,6).reason,'outside');assert.deepEqual(g.place('reserve:0',1,2),{ok:false,reason:'differentRank',from:1,to:2});assert.equal(g.place('reserve:2',1,2).reason,'differentKind');assert.equal(JSON.stringify(g),before);});
test('bench is free and consumed once in ready and combat',()=>{for(const stage of ['ready','wave']){const g=fresh();g.stage=stage;const before=JSON.stringify(g);assert.ok(g.preview('reserve:2',2,2).ok);assert.equal(JSON.stringify(g),before);assert.ok(g.place('reserve:2',2,2).ok);assert.equal(g.coins,0);assert.equal(g.reserve[2],null);assert.equal(g.place('reserve:2',2,2).ok,false);assert.equal(g.units.length,3);assert.equal(g.tray,null);}});
test('bench merges directly, only actual same-tier pairs are cued, rank cap applies',()=>{const g=fresh();assert.equal(g.partner('reserve:0'),null);assert.equal(g.partner('reserve:1'),g.units[1].id);assert.equal(g.place('reserve:1',1,4).type,'merge');assert.equal(g.units.find(u=>u.kind==='rail').rank,2);assert.equal(g.partner('reserve:1'),null);g.units[0].rank=4;g.tray={kind:'spring',rank:4};assert.equal(g.place('tray',1,2).reason,'maxRank');assert.equal(g.partner('tray'),null);});
test('paused, upgrade and ended actions cannot consume sources',()=>{for(const state of ['pause','choice','ended']){const g=fresh();if(state==='pause')g.paused=true;if(state==='choice')g.choices=['supplies'];if(state==='ended')g.stage='win';const before=JSON.stringify(g);assert.equal(g.place('reserve:2',2,2).ok,false);assert.equal(g.sell(g.units[0].id),false);assert.equal(g.refresh(true).ok,false);assert.equal(g.startWave(),false);g.tick(.05);assert.equal(JSON.stringify(g),before);}});
test('salvage only deployed units; cannot repeat-credit a bench slot',()=>{const g=fresh();assert.equal(g.sell('reserve:0'),false);assert.equal(g.sell(g.units[0].id),true);assert.equal(g.coins,1);g.startWave();assert.equal(g.sell(g.units[0].id),false);});
test('refresh costs 5 once and confirms replacement before changing RNG or money',()=>{const g=fresh();assert.equal(g.refresh().reason,'noCoins');g.coins=10;const before=JSON.stringify(g);assert.equal(g.refresh().reason,'replaceReserve');assert.equal(JSON.stringify(g),before);const units=g.lineup();assert.ok(g.refresh(true).ok);assert.equal(g.coins,5);assert.deepEqual(g.lineup(),units);assert.equal(g.reserve.filter(Boolean).length,3);g.reserve=[null,null,null];assert.ok(g.refresh().ok);assert.equal(g.coins,0);const p=g.reserveMove();assert.ok(g.place(p.source,p.c,p.r).ok);assert.equal(g.coins,0);});
test('wave reward once; guided refresh spends earned 5 then drag is free',()=>{const g=tutorial();g.place('reserve:2',2,2);g.place('reserve:1',1,4);g.startWave();run(g,4000);assert.equal(g.stage,'ready');assert.equal(g.wave,1);assert.equal(g.lesson,'refresh');const coins=g.coins;run(g);assert.equal(g.coins,coins);assert.ok(g.refresh(true).ok);assert.equal(g.coins,coins-5);assert.equal(g.lesson,'place');const p=g.reserveMove();assert.ok(p);g.place(p.source,p.c,p.r);assert.equal(g.lesson,'done');assert.equal(g.coins,coins-5);});
test('skip refresh lesson without hidden restock or reward',()=>{const g=tutorial();g.lesson='refresh';const before=structuredClone(g.reserve),rev=g.shopRevision;assert.ok(g.startWave());assert.equal(g.lesson,'done');assert.equal(g.shopRevision,rev);assert.deepEqual(g.reserve,before);});
test('expansion happens once with visual feedback',()=>{const g=new Workshop();assert.equal(g.expand(),false);g.place('tray',1,2);run(g,300);g.place('tray',1,2);g.paused=true;assert.equal(g.expand(),false);g.paused=false;assert.ok(g.expand());assert.equal(g.board.filter(Boolean).length,15);assert.ok(g.effects.some(e=>e.type==='expand'));assert.equal(g.expand(),false);});
test('fusion frees two cells and remains separate from XP',()=>{const g=new Workshop();g.reset('lab');const before=g.units.flatMap(occupied).length;assert.equal(g.place(g.units[0].id,0,3).type,'fusion');assert.equal(before-g.units.flatMap(occupied).length,2);g.place('tray',0,0);g.startWave();run(g,6000);assert.equal(g.stage,'labend');assert.equal(g.xp,0);});
test('XP options target active kinds, freeze time, apply once, use separate RNG',()=>{const g=fresh();g.xp=6;const seed=g.seed;g.offerUpgrades();assert.equal(g.choices.length,3);assert.ok(g.choices.every(id=>!id.startsWith('mortar')&&id!=='repair'));const before=JSON.stringify(g);new SimulationClock().advance(g,.05,2);assert.equal(JSON.stringify(g),before);assert.equal(g.seed,seed);assert.equal(g.chooseUpgrade(9),false);assert.ok(g.chooseUpgrade(0));assert.equal(g.upgradeLevel,1);assert.equal(g.upgradeLog.length,1);assert.equal(g.chooseUpgrade(0),false);});
test('first three cumulative thresholds, no repeated buffs; detached reports and retry reset',()=>{const g=fresh();g.xp=40;for(let n=0;n<3;n++){g.offerUpgrades();assert.equal(g.choices.length,3);assert.ok(g.choices.every(id=>!g.buffs.includes(id)));g.chooseUpgrade(0);}assert.equal(g.choices.length,0);const report=g.report();g.buffs.push('mortar-radius');assert.notDeepEqual(g.buffs,report.buffs);g.retry();assert.deepEqual(g.buffs,[]);assert.equal(g.xp,0);assert.equal(g.upgradeLog.length,0);assert.equal(g.upgradeSeed,4517);assert.equal(report.upgrades.length,3);});
test('supply and repair exact amounts, no useless post-win choices',()=>{const g=fresh();g.choices=['supplies'];g.chooseUpgrade(0);assert.equal(g.coins,5);g.hp=90;g.choices=['repair'];g.chooseUpgrade(0);assert.equal(g.hp,100);g.stage='win';g.xp=100;g.offerUpgrades();assert.equal(g.choices.length,0);});
function fire(kind,buff,distances){const g=fresh();g.units=[];g.stage='wave';g.spawnLeft=1;g.spawnTime=99;g.add(kind,1,0,0);g.units[0].cooldown=0;if(buff)g.buffs=[buff];for(const d of distances){g.spawn(100,false,'patrol',0);g.enemies.at(-1).d=d;}g.tick(1/60);return g;}
test('spring bounce, blast radius and attack speed have real combat effects',()=>{assert.deepEqual(fire('spring',null,[80,100]).enemies.map(e=>e.hp),[100,88]);assert.deepEqual(fire('spring','spring-bounce',[80,100]).enemies.map(e=>e.hp),[94,88]);assert.deepEqual(fire('mortar',null,[40,100]).enemies.map(e=>e.hp),[100,82]);assert.deepEqual(fire('mortar','mortar-radius',[40,100]).enemies.map(e=>e.hp),[82,82]);assert.equal(fire('spring','spring-speed',[100]).units[0].cooldown,.85/1.25);});
test('rail pierce hits four collinear enemies instead of three',()=>{assert.equal(fire('rail',null,[110,114,118,122]).enemies.filter(e=>e.hp<100).length,3);assert.equal(fire('rail','rail-pierce',[110,114,118,122]).enemies.filter(e=>e.hp<100).length,4);});
test('range matters and blast bypasses armor',()=>{const g=fresh();g.units=[];g.stage='wave';g.spawnLeft=1;g.spawnTime=99;g.spawn(100,false,'armor',0);g.enemies[0].d=100;const u=g.add('spring',1,5,4);u.cooldown=0;g.tick(.01);assert.equal(g.enemies[0].hp,100);u.c=0;u.r=0;u.cooldown=0;g.tick(.01);assert.equal(g.enemies[0].hp,92.2);u.kind='mortar';u.cooldown=0;g.tick(.01);assert.equal(g.enemies[0].hp,74.2);});
test('path ends at parts box',()=>assert.deepEqual(pointAt(LENGTH),[26,346]));
test('deployment exposes only read-only health',async()=>{const{handleApi}=await import('../worker/index.js');assert.equal((await handleApi(new Request('https://example.test/api/health'))).status,200);assert.equal((await handleApi(new Request('https://example.test/api/save'))).status,404);});
