import {createRequire} from 'node:module';
import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
const {chromium}=createRequire('/Users/yin/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/package.json')('playwright');
const base=process.env.QA_BASE||'http://127.0.0.1:5193/',phase=process.env.QA_PASS||'after',out=`_qa/guide-r27/${phase}`;await fs.mkdir(out,{recursive:true});const browser=await chromium.launch(),results=[];
try{for(const [width,height]of[[320,568],[390,844]]){
 const ctx=await browser.newContext({viewport:{width,height},isMobile:true,hasTouch:true}),p=await ctx.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.clock.install();await p.goto(base+'?lang=zh');await p.locator('.tw[data-renderer=pixel]').waitFor({timeout:60000});const step=n=>p.clock.runFor(n),act=async s=>{await p.locator(s).tap();await step(50);};
 const check=async(name,w,h)=>{await act('[data-action=hint]');await step(1350);const m=await p.evaluate(()=>{const hand=document.querySelector('.tw__guide-hand'),c=hand.querySelector('canvas'),img=hand.querySelector('img'),cell=document.querySelector('[data-cell]').getBoundingClientRect();return{cells:[...document.querySelectorAll('.tw-guide-target')].map(e=>e.dataset.cell),w:+c.dataset.footWidth,h:+c.dataset.footHeight,cell:cell.width,imgZ:getComputedStyle(img).zIndex,canvasZ:getComputedStyle(c).zIndex};});if(phase!=='before'){assert.equal(m.cells.length,w*h);assert(Math.abs(m.w-w*m.cell)<1);assert(Math.abs(m.h-h*m.cell)<1);assert(+m.imgZ>+m.canvasZ);}await p.screenshot({path:`${out}/${width}-${name}.png`});results.push({width,name,...m});};
 await check('spring',1,2);await act('[data-source=tray]');await act('[data-cell="0,0"]');await step(5000);assert.equal(await p.locator('.tw').getAttribute('data-stage'),'second');await check('merge',1,2);await act('[data-source=tray]');await act('[data-cell="0,0"]');await check('land',2,1);await act('[data-source=land]');await act('[data-cell="0,3"]');await check('rail',3,1);await act('[data-source=tray]');await act('[data-cell="0,2"]');assert.equal(await p.locator('.tw').getAttribute('data-stage'),'ready');assert.deepEqual(errors,[]);await ctx.close();
}}finally{await browser.close();}await fs.writeFile(`${out}/checks.json`,JSON.stringify(results,null,2));console.log(results);
