import {createRequire} from 'node:module';
import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
const {chromium}=createRequire('/Users/yin/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/package.json')('playwright');
const base=process.env.QA_BASE||'http://127.0.0.1:5193/',phase=process.env.QA_PASS||'after',out=`_qa/help-r26/${phase}`;await fs.mkdir(out,{recursive:true});const browser=await chromium.launch(),results=[];
try{for(const [width,height,lang]of[[320,568,'en'],[390,844,'zh']]){
 const ctx=await browser.newContext({viewport:{width,height},isMobile:true,hasTouch:true}),p=await ctx.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.clock.install();await p.goto(base+'?lang='+lang);await p.locator('.tw[data-renderer=pixel]').waitFor({timeout:60000});await p.evaluate(()=>document.fonts.ready);await p.clock.runFor(500);
 const b=p.locator('[data-action=hint]'),metrics=await b.evaluate(e=>{const r=e.getBoundingClientRect(),s=getComputedStyle(e);return{w:r.width,h:r.height,font:s.fontFamily,size:s.fontSize,border:s.borderImageSource,label:e.getAttribute('aria-label'),text:e.textContent,loaded:document.fonts.check('32px "Jersey 10"','?')};});assert(metrics.w>=44&&metrics.h>=44&&metrics.label);if(phase!=='before'){assert(metrics.font.includes('Jersey 10'));assert(metrics.loaded);assert(metrics.border.includes('lilac-blank'));assert.equal(metrics.size,'32px');}
 await p.screenshot({path:`${out}/${width}-entry.png`});await b.screenshot({path:`${out}/${width}-button.png`});await b.focus();await p.screenshot({path:`${out}/${width}-focus.png`});await p.keyboard.press('Enter');await p.clock.runFor(100);assert.equal(await p.locator('.tw').getAttribute('data-stage'),'place');assert(await p.locator('.tw__guide').isVisible());await b.tap();await p.clock.runFor(100);assert(await p.locator('.tw__guide').isVisible());await p.locator('[data-action=pause]').tap();await p.clock.runFor(300);assert.equal(await b.evaluate(e=>Boolean(e.closest('[inert]'))),true);await p.locator('[data-action=resume]').tap();await p.clock.runFor(300);await b.tap();assert.deepEqual(errors,[]);results.push({width,height,lang,metrics,errors});await ctx.close();
}}finally{await browser.close();}await fs.writeFile(`${out}/checks.json`,JSON.stringify(results,null,2));console.log(results);
