import {createRequire} from 'node:module';import fs from 'node:fs/promises';import assert from 'node:assert/strict';
const {chromium}=createRequire('/Users/yin/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/package.json')('playwright');
const base=process.env.QA_PIXEL_BASE||'http://127.0.0.1:5193/pixel-lab/',out=process.env.QA_BATTLE_OUT||'_qa/battle-recheck';await fs.mkdir(out,{recursive:true});const browser=await chromium.launch(),results=[];
try{for(const[width,height,lang]of[[1440,1000,'zh'],[390,844,'zh'],[320,568,'en']]){
 const context=await browser.newContext({viewport:{width,height},hasTouch:width<700,recordVideo:{dir:out}}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(base+`?section=combat&lang=${lang}`);await page.locator('.px-battle[data-ready=true]').waitFor({timeout:60000});await page.evaluate(()=>document.fonts.ready);await page.clock.install();
 const host=page.locator('.px-battle'),game=page.locator('.px-game');const step=async ms=>{await page.clock.runFor(ms);};
 for(const weapon of['spring','rail','mortar','bubble','drum','fusion']){
  await page.locator(`[data-battle-weapon=${weapon}]`).click();const before=await page.locator('.px-board').boundingBox();const hashes=[];
  for(const r of weapon==='fusion'?[4]:[1,2,3,4]){if(weapon!=='fusion')await page.locator(`[data-battle-rank="${r}"]`).click();await step(500);hashes.push(await page.locator('.px-battle-actor').first().evaluate(c=>c.toDataURL()));const box=await page.locator('.px-board').boundingBox();assert.equal(box.width,before.width);assert.equal(box.height,before.height);
   const rank=await page.locator('.px-board .px-rank').first().boundingBox(),unit=await page.locator('.px-machine').first().boundingBox();assert(rank.width<32);assert(rank.x-unit.x<6);assert(unit.y+unit.height-(rank.y+rank.height)<6);if(r===1||r===4)await game.screenshot({path:`${out}/${width}-${weapon}-tier${r}.png`});}
  if(weapon!=='fusion')assert.equal(new Set(hashes).size,4,'structural upgrade must change canvas pixels');
  await page.locator('[data-battle=start]').click();await step(1800);const shots=JSON.parse(await host.getAttribute('data-shots'));assert((shots[weapon==='drum'?'spring':weapon]||0)>0);for(let j=0;j<110&&Number(await host.getAttribute('data-effects'))===0;j++)await step(16);await step(60);await game.screenshot({path:`${out}/${width}-${weapon}-hit.png`});await page.locator('[data-battle=pause]:not([inert] *)').first().click();const frozen=await host.getAttribute('data-elapsed');await step(500);assert.equal(await host.getAttribute('data-elapsed'),frozen);await page.locator('[data-battle=reset]:not([inert] *)').click();
 }
 for(const enemy of['patrol','runner','swarm','armor','boss']){await page.locator('[data-battle-weapon=bubble]').click();await page.locator('[data-battle-rank="1"]').click();await page.locator(`[data-battle-enemy=${enemy}]`).click();await page.locator('[data-battle=start]').click();await step(1500);const frames=new Set();for(let i=0;i<5;i++){await step(130);frames.add(JSON.parse(await host.getAttribute('data-frames'))[enemy]);}assert(frames.size>1,enemy+' walk changes actual frames');await game.screenshot({path:`${out}/${width}-enemy-${enemy}.png`});await page.locator('[data-battle=reset]:not([inert] *)').click();}
 await page.locator('.px-battle__details summary').first().click();for(const phase of['early','control','support','fusion']){await page.locator(`[data-battle-phase=${phase}]`).click();assert.equal(await host.getAttribute('data-phase'),phase);await page.locator('[data-battle=start]').click();await step(2600);await game.screenshot({path:`${out}/${width}-phase-${phase}.png`});await page.locator('[data-battle=reset]:not([inert] *)').click();}
 await page.locator('[data-battle-weapon=spring]').click();await page.locator('[data-battle-enemy=patrol]').click();await page.locator('[data-battle-rank="4"]').click();await page.locator('[data-battle=start]').click();
 for(let i=0;i<35&&(await host.getAttribute('data-stage'))!=='win';i++){await step(1000);if(await page.locator('[data-battle-choice]').count()){await page.locator('[data-battle-choice]').first().click();}}
 assert.equal(await host.getAttribute('data-stage'),'win');await step(1000);assert.equal(await host.getAttribute('data-effects'),'0');await game.screenshot({path:`${out}/${width}-win.png`});await page.locator('[data-battle=reset]:not([inert] *)').first().click();await page.locator('[data-battle=clear]').click();await page.locator('[data-battle=start]').click();await step(45000);assert.equal(await host.getAttribute('data-stage'),'lose');assert.equal(await host.getAttribute('data-hp'),'0');await game.screenshot({path:`${out}/${width}-lose.png`});await page.locator('[data-battle=reset]:not([inert] *)').first().click();
 assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:`${out}/${width}-full.png`,fullPage:true});assert.deepEqual(errors,[]);
 await page.emulateMedia({reducedMotion:'reduce'});await page.locator('[data-battle-enemy=runner]').click();await page.locator('[data-battle=start]').click();await step(1700);assert.equal(JSON.parse(await host.getAttribute('data-frames')).runner,0);
 await page.locator('[data-action="section:aim"]').click();await page.locator('.px-aim[data-ready=true]').waitFor();assert.equal(await page.locator('.px-battle-fx').count(),0);results.push({width,height,lang,status:'passed'});await context.close();
 }
 const context=await browser.newContext(),page=await context.newPage();await page.route('**/battle-v1/fx/rail/sheet.png',r=>r.abort());await page.goto(base+'?section=combat');await page.locator('.px-battle[data-ready=error]').waitFor({timeout:60000});assert(await page.locator('[data-battle=start]').isDisabled());await page.unroute('**/battle-v1/fx/rail/sheet.png');await page.locator('[data-battle=retry]').click();await page.locator('.px-battle[data-ready=true]').waitFor({timeout:60000});await context.close();
 await fs.writeFile(out+'/results.json',JSON.stringify({base,results,errorRecovery:'passed',clock:'virtual time for mechanical coverage; real-time capture separate'},null,2));console.log(results);
}finally{await browser.close();}
