import {createRequire} from 'node:module';import fs from 'node:fs/promises';import assert from 'node:assert/strict';
const {chromium}=createRequire('/Users/yin/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/package.json')('playwright');
const base=process.env.QA_PIXEL_BASE||'http://127.0.0.1:5193/pixel-lab/',out=process.env.QA_AIM_OUT||'_qa/pixel-aim';await fs.mkdir(out,{recursive:true});
const browser=await chromium.launch(),results=[];
try{for(const [width,height,lang]of [[1440,1000,'zh'],[390,844,'zh'],[320,568,'en']]){
 const context=await browser.newContext({viewport:{width,height},hasTouch:width<700,recordVideo:{dir:out}}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(base+`?section=aim&lang=${lang}`,{waitUntil:'domcontentloaded',timeout:60000});await page.locator('.px-aim[data-ready="true"]').waitFor({timeout:60000});await page.locator('.px-game img').evaluateAll(imgs=>Promise.all(imgs.map(i=>i.decode())));await page.evaluate(()=>document.fonts.ready);
 assert.equal(await page.locator('.px-aim-actor').count(),3);const originalBox=await page.locator('.px-board').boundingBox();const seen={mortar:new Set(),bubble:new Set(),rail:new Set()};
 for(let i=0;i<8;i++){await page.locator(`[data-aim-position="${i}"]`).click();await page.waitForTimeout(1050);const dirs=await page.locator('.px-aim-actor').evaluateAll(cs=>cs.map(c=>[c.dataset.kind,Number(c.dataset.direction)]));for(const[k,d]of dirs)seen[k].add(d);const b=await page.locator('.px-board').boundingBox();assert.equal(b.width,originalBox.width);assert.equal(b.height,originalBox.height);if([0,2,4,6].includes(i))await page.locator('.px-game').screenshot({path:`${out}/${width}-${lang}-direction-${i}.png`});}
 for(const[k,s]of Object.entries(seen))assert(s.size>=4,`${k} must visibly turn across at least four directions`);
 await page.locator('[data-aim="fire"]').click();await page.waitForFunction(()=>Number(document.querySelector('.px-aim').dataset.hits)>=3);for(const n of await page.locator('.px-aim-actor').evaluateAll(cs=>cs.map(c=>Number(c.dataset.shots))))assert(n>=1);
 await page.locator('[data-aim="clear"]').click();assert(await page.locator('.px-aim-target').isHidden());assert(await page.locator('[data-aim="fire"]').isDisabled());
 await page.locator('[data-aim-position="0"]').click();const target=page.locator('.px-aim-target');await target.focus();const left=await target.evaluate(e=>parseFloat(e.style.left));await page.keyboard.press('ArrowLeft');assert((await target.evaluate(e=>parseFloat(e.style.left)))<left);
 await page.locator('.px-game').scrollIntoViewIfNeeded();const w=await page.locator('.px-world').boundingBox();
 const from=await target.boundingBox(),start={x:from.x+22,y:from.y+22},end={x:w.x+w.width*.3,y:w.y+w.height*.8};
 if(width<700){const cdp=await context.newCDPSession(page);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[start]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[end]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});}else{await page.mouse.move(start.x,start.y);await page.mouse.down();await page.mouse.move(end.x,end.y,{steps:8});await page.mouse.up();}
 assert(Math.abs((await target.evaluate(e=>parseFloat(e.style.left)))-30)<1);
 await page.locator('[data-aim="static"]').click();assert.equal(await page.locator('.px-aim-actor:visible').count(),0);await page.locator('.px-game').screenshot({path:`${out}/${width}-${lang}-static.png`});await page.locator('[data-aim="static"]').click();assert.equal(await page.locator('.px-aim-actor:visible').count(),3);
 await page.locator('[data-aim="auto"]').click();await page.locator('.px-game').scrollIntoViewIfNeeded();await page.waitForTimeout(1700);await page.locator('[data-aim="pause"]').click();const frozen=await target.getAttribute('style');await page.waitForTimeout(250);assert.equal(await target.getAttribute('style'),frozen);
 assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:`${out}/${width}-${lang}-full.png`,fullPage:true});await page.emulateMedia({reducedMotion:'reduce'});await page.reload({waitUntil:'domcontentloaded'});await page.locator('.px-aim[data-ready="true"]').waitFor({timeout:60000});assert.equal(await page.locator('[data-aim="auto"]').getAttribute('aria-pressed'),'false');
 await page.locator('[data-action="section:animation"]').click();await page.locator('.px-animation[data-ready="true"]').waitFor({timeout:60000});assert.equal(await page.locator('.px-aim-target').count(),0);assert.deepEqual(errors,[]);results.push({width,height,lang,status:'passed',directions:Object.fromEntries(Object.entries(seen).map(([k,s])=>[k,[...s]]))});await context.close();
 }
 const c=await browser.newContext(),p=await c.newPage();await p.route('**/aim-v1/bubble/head-0.png',r=>r.abort());await p.goto(base+'?section=aim',{waitUntil:'domcontentloaded'});await p.locator('.px-aim[data-ready="error"]').waitFor({timeout:60000});assert.equal(await p.locator('.px-aim-actor:visible').count(),0);assert(await p.locator('[data-aim="fire"]').isDisabled());await p.unroute('**/aim-v1/bubble/head-0.png');await p.locator('[data-aim="retry"]').click();await p.locator('.px-aim[data-ready="true"]').waitFor({timeout:60000});await c.close();
 await fs.writeFile(`${out}/results.json`,JSON.stringify({base,results,errorRecovery:'passed'},null,2));console.log(results);
}finally{await browser.close();}
