const copy = {
 'benchFusion-first':['可融合','Fuse'],'benchFusion-next':['可融合','Fuse'],benchFusionPlace:['拖到另一件上融合','Drag onto its partner to fuse'],benchFusionReady:['配方已齐 · 拖到棋盘武器上融合','Pair ready · Drag onto its board partner'],benchFusionSpace:['配方已齐 · 先扩格或整理','Pair ready · Expand or rearrange first'],benchFusionConfirm:['不消耗齿轮 · 产物留在台子上','No gear cost · Result stays on the bench'],benchFused:['融合完成 · 拖上棋盘参战','Fused · Drag onto the board to deploy'],confirmFusion:['请先确认融合','Confirm fusion first'],
routeKitIntro:['2阶材料 · 亲手拖拽融合','Tier 2 parts · Drag to fuse'],routeKitReplace:['替换候补武器，保留地块','Replaces tray weapons; keeps tiles'],routeKitClaim:['领取 · 5齿轮','Get kit · 5 gears'],frostKit:['范围减速40% · 2×2格\n放弃弹簧直击与弹射','40% area slow · 2×2\nLoses Spring fire / ricochet'],stormKit:['连锁4目标 · 3×2格\n放弃直线穿透','4 chained targets · 3×2\nLoses straight piercing'],
routeSupply:['融合补给','Fusion kit'],routeSupplyHint:['本关限一次 · 5齿轮','Once per level · 5 gears'],routeSupplyBody:['选两件2阶材料，亲手拖拽融合。也可分开使用。','Choose two tier 2 parts. Drag to fuse, or use them separately.'],routeReplace:['将替换下方剩余武器，地块保留。','Replaces remaining tray weapons. Expansion tiles are kept.'],routeClaim:['选这组 · 5齿轮','Choose kit · 5 gears'],routeSkip:['先不选','Not now'],routeDelivered:['材料已送到下方 · 先放置，再拖拽融合','Parts in tray · Place the anchor, then drag its partner onto it'],routeNeed:['＋{name} · {n}阶','+ {name} · T{n}'],
frostRecipe3:['3阶霜泡塔 · 2×2格\n范围减速40%，牺牲弹簧直击与弹射。','Tier 3 Frost · 2×2 cells\n40% area slow. Loses Spring direct fire and ricochet.'],
stormRecipe3:['3阶雷网炮 · 3×2格\n连锁4个目标，腾出1格；失去直线穿透。','Tier 3 Storm · 3×2 cells\nChains 4 targets, frees 1 cell. Loses straight-line piercing.'],
landCredit:['可扩 {n} 格','{n} cells available'],recoverTitle:['继续上次防守？','Continue your defense?'],recoverBody:['第 {n} 关 · 已进行 {wave} 波\n继续保留原阵地；重新开始使用中央布局。仅保存在这台设备。','Level {n} · Wave {wave}\nContinue keeps your layout; restart uses the centered board. Saved on this device.'],recoverRun:['继续防守','Continue defense'],recoverNew:['重新开始教学','Restart tutorial'],saveUnavailable:['无法自动保存，请勿关闭本页','Auto-save unavailable. Keep this page open.'],saveInvalid:['旧存档无法恢复，已准备新游戏','Save could not be restored. A new game is ready.'],
handbook:['构筑手册','Build handbook'],chapterSupply:['供给节奏','Supply rhythm'],afterWave:['第 {n} 波后','After wave {n}'],tierSupply:['主要供应2阶武器','Mainly tier 2 machines'],landSchedule:['扩格：初始3格；第1波后3格，第2—4波后各4格，第5/6波后各6格','Land: 3 initially; +3 after wave 1, +4 after waves 2–4, +6 after waves 5–6'],routeChoices:['可选融合方向','Optional fusion routes'],routeOptional:['新路线2+2→3阶，也可3+3→4阶。第4关起，第2波后有一次定向补给。融合不是必选。','New routes: 2+2 → tier 3, or 3+3 → tier 4. One kit after wave 2 from level 4 onward. Fusion is optional.'],
frost:['霜泡塔','Frost tower'],storm:['雷网炮','Storm lattice'],fusionSpace:['融合需要更大的连续空间','Fusion needs more connected space'],
frostRecipe:['霜泡塔 · 2×2格\n范围减速50%，以控场换直击火力。不继承弹簧弹射。','Frost tower · 2×2 cells\n50% area slow, less direct firepower. Spring ricochet is not inherited.'],
stormRecipe:['雷网炮 · 3×2格\n最多连锁6个目标，腾出1格；放弃磁轨直线穿透。','Storm lattice · 3×2 cells\nChain up to 6 targets; free 1 cell. Rail piercing is lost.'],
mixedWave:['重甲掩护快兵','Armor covers runners'],
swapBlocked:['交换后空间不足','Not enough room to swap'],swapDone:['已交换位置','Positions swapped'],reserveMerged:['合成 {n} 阶','Merged to tier {n}'],
reportTitle:['本波复盘','Wave breakdown'],reportEscaped:['漏过的敌人','Escaped enemies'],reportClean:['本波没有漏怪','No escapes this wave'],reportDamage:['主要输出','Top damage'],reportRemaining:['平均剩余血量 {n}%','Average health left: {n}%'],
reportDamageNote:['按种类合计，不含溢出伤害；辅助另列。','By type, excluding overkill. Support shown separately.'],reportNoDamage:['本波没有有效伤害','No effective damage this wave'],
reportBreach:['破甲增伤 +{n}','Armor-break bonus +{n}'],reportSupport:['鼓舞射击 {n} 次','Boosted shots: {n}'],reportChain:['连锁命中 {n} 次','Chain target hits: {n}'],reportFailure:['本波漏过最多：{name} × {n}','Most escapes this wave: {name} × {n}'],
reportNear:['差一点击倒：可尝试减速或补出口火力。','Nearly defeated: try slowing enemies or covering the exit.'],reportArmor:['可尝试破甲协作，或集中覆盖重甲路线。','Try armor break or focus fire along the armored route.'],reportCrowd:['可尝试连锁或范围火力，照顾分裂后的幼虫。','Try chain or area attacks to catch the spawned mites.'],reportBoss:['可尝试加强单体输出和首领沿途覆盖。','Try more single-target damage and coverage along the boss route.'],reportCoverage:['可尝试调整射程覆盖，减少敌人空跑的路段。','Try repositioning to cover unprotected route sections.'],
rivet:['铆钉枪','Rivet gun'],arc:['电弧线圈','Arc coil'],rivetBrief:['破甲后，队友更强','Break armor for your allies'],arcBrief:['电弧连跳邻近敌人','Chain through nearby enemies'],
trialRules:['试验规则：铆钉占1×3格，破甲3秒，护甲减伤降低60%，不叠加。电弧占2×2格，最多连中3个近邻，每跳70%伤害。重盾减伤60%；分裂壳死后生2只幼虫，幼虫不掉经验。新武器造型为组件试制。','Trial rules: Rivet uses 1×3 cells and reduces armor mitigation by 60% for 3 seconds, without stacking. Arc uses 2×2 cells, hitting up to 3 neighbors at 70% damage per hop. Shield guards mitigate 60%; brood shells spawn 2 mites that award no XP. New weapon art is component-built.'],
level5:['装甲围城','Armored siege'],level6:['裂群风暴','Splitter storm'],focus5:['铆钉破甲 · 队友集火','Break armor · Focus allied fire'],focus6:['分裂成群 · 连锁清场','Splitters · Chain the crowd'],
plated:['重盾卫','Shield guard'],brood:['分裂壳','Brood shell'],mite:['幼虫','Mite'],
'rivet-duration':['深度破甲','Deep breach'],'rivet-durationDesc':['削甲 60% → 80% · 持续 5 秒','Armor reduction 60% → 80% · Lasts 5s'],
'arc-chain':['多级放电','Extra arc'],'arc-chainDesc':['连锁目标 3 → 4 个','Chain targets 3 → 4'],
benchLand:['扩格','Land'],benchWeapons:['武器','Guns'],switchLand:['切换到地块','Show land pieces'],switchWeapons:['切换回武器','Show weapons'],noLand:['暂无可用地块','No land available'],openLandHint:['点地块，扩建阵地','Tap land to expand'],
loadingTitle:['玩具大暴走','Toy Rampage'],
loadingWorkshop:['正在装配工坊','Assembling the workshop'],
loadingAssets:['素材准备进度','Assets prepared'],
loadingHint:['准备完成后即可进入','Enter when everything is ready'],
loadingSlow:['网络较慢，正在继续准备…','Slow connection. Still preparing…'],
loadingErrorAssets:['素材没有加载完整，请重试。','Some artwork failed to load. Please retry.'],
retryLoading:['重新加载','Retry loading'],
"bubble":["泡泡枪","Bubble"],
"drum":["发条鼓","Drum"],
"plot2":["扩2格","Add 2 cells"],
"plot1":["填1格","Add 1 cell"],
"locked":["尚未扩建","Not built yet"],
"landBrief":["选一块，向外扩","Choose a shape, expand outward"],
rotateLand:['旋转90°','Rotate 90°'],chooseLand:['切换直条 / L形','Switch bar / L shape'],shapeLand:['换形','Shape'],splitLand:['拆格','Split'],rotateLandHint:['转一转，再放','Rotate to fit'],
plot4:['方形四格','Four-cell square'],plotV2:['竖向两格','Vertical pair'],plot3:['直线三格','Three-cell bar'],plotV3:['竖向三格','Vertical three'],plotL0:['L形三格','L-shaped land'],plotL1:['L形三格','L-shaped land'],plotL2:['L形三格','L-shaped land'],plotL3:['L形三格','L-shaped land'],
"bubbleBrief":["泡泡命中，敌人减速","Bubbles slow enemies"],
"drumBrief":["鼓放在炮旁，加快攻击","Put the drum beside a gun"],
"landOverlap":["地块要放在未扩建的格子。","Place land on unbuilt cells."],
"landConnect":["地块要紧挨已有阵地。","Connect land to your board."],
"lockedCell":["这里还没地块，先扩建。","Add land here first."],
"fusionAction":["融合","Fuse"],
"fuseNow":["合成新发明","Build the invention"],
"bubble-splash":["连环泡泡","Bubble splash"],
"bubble-splashDesc":["周围敌人也减速","Nearby enemies are slowed too"],
"bubble-speed":["泡泡连发","Rapid bubbles"],
"bubble-speedDesc":["泡泡枪攻速 +25%","Bubble attack speed +25%"],
"drum-boost":["强力鼓舞","Louder drum"],
"drum-boostDesc":["邻接攻速加成再 +10%","Adjacent speed bonus +10 percentage points"],
'look-block':['A · 积木','A · Block'],'look-open':['B · 留白','B · Open'],switchBlock:['切换到A饱满积木外观','Switch to A: solid blocks'],switchOpen:['切换到B留白玩具外观','Switch to B: open toys'],switchLook:['切换外观','Switch look'],lookHint:['只换外观，占格和数值不变。','Only the look changes. Footprints and stats stay the same.'],
canMerge:['可合成','Can merge'],xpLabel:['击杀 → 强化','Kills → Upgrade'],xpDone:['强化完成','Upgrades complete'],upgradeTitle:['升级，选一项强化','Level up · Choose one'],upgradeIntro:['战斗已暂停，选完继续','Battle paused until you choose'],affects:['作用于 {n} 台 · 后续同类也生效','Affects {n} · Future matching machines too'],instantReward:['立即获得','Gain instantly'],chosenUpgrades:['本关强化','Chosen upgrades'],
'spring-bounce':['弹簧弹射','Spring ricochet'],'spring-bounceDesc':['再弹向1个敌人 · 50%伤害','Bounce to 1 more enemy · 50% damage'],
'rail-pierce':['宽轨贯穿','Wide rail'],'rail-pierceDesc':['穿透3→4个 · 更宽弹道','Pierce 3 → 4 · Wider line'],
'mortar-radius':['大爆米花','Big popcorn'],'mortar-radiusDesc':['爆炸更大 · 半径 +42%','Bigger blast · Radius +42%'],
'spring-speed':['弹簧加速','Rapid spring'],'spring-speedDesc':['弹簧炮攻速 +25%','Spring attack speed +25%'],
'rail-speed':['磁轨加速','Rapid rail'],'rail-speedDesc':['磁轨炮攻速 +25%','Rail attack speed +25%'],
'mortar-speed':['爆米花加速','Rapid popcorn'],'mortar-speedDesc':['爆米花炮攻速 +25%','Popcorn attack speed +25%'],
supplies:['补给齿轮','Gear supply'],suppliesDesc:['+5齿轮 · 可换一批','+5 gears · One new batch'],repair:['修复箱子','Repair the box'],repairDesc:['恢复20生命','Restore 20 health'],
replaceTitle:['替换剩余武器？','Replace remaining machines?'],replaceBody:['备战席还有 {n} 件未上阵。花5齿轮替换为新3件，场上武器不变。','{n} machines remain on the bench. Spend 5 gears to replace them with 3 new ones. Your board stays unchanged.'],replaceConfirm:['换新3件 · 5齿轮','Replace all · 5 gears'],
level1:['初次守夜','First night'],level2:['快兵来袭','Quick feet'],level3:['钢铁洪流','Iron tide'],level4:['最后一班','Last shift'],
focus1:['熟悉合成与布阵','Merge and arrange'],focus2:['快兵 · 覆盖路线','Speed · Cover the route'],focus3:['密集重甲 · 搭配火力','Armor · Mix your firepower'],focus4:['混合进攻 · 分配齿轮','Mixed waves · Budget gears'],
levelNumber:['第 {n} 关','Level {n}'],levelCleared:['第 {n} 关，守住了','Level {n} cleared'],
levelShort:['关','LV'],waveUnit:['波','W'],
replayActive:['正在演示，看手势','Watch the hand demonstration'],
chooseLevel:['选择关卡','Choose level'],nextLevel:['下一关','Next level'],retryLevel:['重试本关','Retry this level'],switchLevel:['切换关卡？','Switch level?'],
fixedStart:["4个基础关＋2个机制试验关，各8波。独立起步，首批武器与地块免费。","4 base levels + 2 mechanics trials, 8 waves each. Start fresh with free machines and land."],
records:['本关记录','Run records'],rules:['玩法与教学','Rules & tutorial'],back:['返回','Back'],
recordLabel:['第 {n} 关','Level {n}'],cleared:['通过','Cleared'],failed:['失败','Failed'],abandoned:['中途结束','Stopped early'],inProgress:['进行中','In progress'],
waveShort:['第 {n} 波','Wave {n}'],noRecords:['还没有已结束的波次。','No finished waves yet.'],
recordStats:['击倒 {kills} · 漏过 {leaks} · {seconds} 秒','{kills} defeated · {leaks} escaped · {seconds}s'],
beforeBattle:['开战阵容','Starting build'],afterBattle:['结束阵容','Ending build'],position:['{r} 行 {c} 列','R{r} C{c}'],
exportRecords:['导出测试记录','Export test records'],recordLocal:['仅保留本页当前与最近 20 次记录，刷新会清空。','Current run and up to 20 previous attempts, in this page only. Reload clears records.'],
pastAttempts:['此前尝试','Previous attempts'],currentAttempt:['查看当前尝试','View current attempt'],
free:['免费','Free'],tap:['点这里','Tap here'],
expandLabel:['增加一排，免费解锁 4 格','Add a row: unlock 4 cells free'],
refreshName:['换一批','New batch'],
refreshBrief:['用刚得到的齿轮换一批','Use your gears for a new batch'],
refreshPlaceBrief:['新武器到手，直接拖入','New machines are yours · Drag in'],
makeRoomBrief:['先腾空位，或开始战斗','Make room, or start battle'],
speedLabel:['当前 {n} 倍速度，点击切换','Current speed {n}×; tap to switch'],
rewardShort:['+5 齿轮','+5 gears'],
placeBrief:['拖到亮框','Drag onto the board'],
watchBrief:['自动开火，守住箱子','It fires to protect the box'],
secondBrief:['拖到同阶武器上合并','Drop on a matching tier'],
mergeBrief:['同种同阶，拖到一起','Drag matching machines together'],
expandBrief:["选一块，向外扩","Choose a shape, expand outward"],
railBrief:["拖到连续三格空位","Drag onto three empty cells"],
fusedBrief:['放下备用炮，试射','Place the spare, then test'],
fusionBrief:['拖到另一台上，融合','Drag onto the other to fuse'],
labwaveBrief:['穿透之后，还会爆炸','Pierce, then blast'],
readyBrief:['拖动武器布阵','Drag machines into place'],
compactRules:["备战武器与地块免费拖入，战斗中也能部署。地块须紧挨已有阵地，初始2格，第1/2波后各2格，第3—6波后各3格，从12格扩到30格。可旋转，三格可换直条或L形；所有形状都放不下时可主动拆成单格，额度不变。\n换一批花5齿轮，替换剩余武器，不动地块；波间+5。每批至少1件场上未满阶同类，第4波后以2阶为主；场上有1阶时，首槽补齐同种1阶。拆解1/2/3/4阶返1/1/2/4齿轮。第1/3波后首次换批分别出现泡泡枪/发条鼓。\n同种同阶合成到4阶；3阶弹簧+磁轨、弹簧+泡泡、磁轨+电弧可融合；结果须有连续空间，详见构筑手册。击杀经验暂停并提供1至3个不同强化。泡泡减速35%，首领效果减半；鼓让共边炮攻速+15/20/25/30%，多个鼓取最高。普通漏怪扣20，首领40，守过8波获胜。","Drag owned machines and land for free, even during battle. Land must join built cells along an edge. Grow from 12 to 30 cells: 2 initially, +2 after waves 1–2, +3 after waves 3–6. Rotate pieces; switch three-cell bars and L shapes. If none fit, split into singles without extra credit.\nA batch costs 5 gears, replaces remaining machines, never land. Each wave pays 5. One slot matches a non-maxed kind on your board; after wave 4, batches are mainly tier 2, with slot one pairing an existing tier 1. Salvage tiers 1/2/3/4 for 1/1/2/4 gears. First refresh after wave 1 introduces Bubble; after wave 3, Drum.\nMerge matching tiers up to 4. Tier 3 Spring + Rail, Spring + Bubble, or Rail + Arc can fuse if the result fits; see the build handbook. XP pauses combat for 1–3 distinct upgrades. Bubbles slow 35%, halved on bosses. Drums speed edge-adjacent guns by 15/20/25/30%; only the strongest applies. Escapes cost 20 health, bosses 40. Survive 8 waves."],
title:['玩具工坊','Toy Workshop'],edition:['v0.5.0','v0.5.0'],health:['生命','Health'],coins:['齿轮','Gears'],safe:['练习','Practice'],wave:["{n} / {total} 波","Wave {n} / {total}"],remaining:['剩余 {n}','{n} remaining'],lab:['配方实验','Fusion lab'],
spring:['弹簧炮','Spring'],rail:['磁轨炮','Rail'],mortar:['爆米花炮','Popcorn'],fusion:['爆裂轨道炮','Burst rail'],
springDesc:['单体 · 占 1×2','Single · 1×2'],railDesc:['穿透 · 占 3×1','Pierce · 3×1'],mortarDesc:['爆炸破甲 · 占 2×2','Blast · 2×2'],fusionDesc:['穿透＋爆炸 · 占 3×1','Pierce + blast · 3×1'],
unit:['{name} · {n} 阶','{name} · Tier {n}'],select:['选中 {name}','Select {name}'],cell:['第 {r} 行，第 {c} 格','Row {r}, column {c}'],board:['工作板','Workboard'],goal:['守住这里','Protect'],
placeTitle:['拖进工作板，让它开工','Drag it onto the board'],placeBody:['跟着手指拖动。也可先点炮，再点亮框。','Follow the hand. Or tap the cannon, then a lit cell.'],
watchTitle:['看，它会自动开火','It fires automatically'],watchBody:['击倒眼前的练习敌人。现在不会扣血。','Watch it defeat the practice enemy. Your box is safe.'],
secondTitle:['相同的两台，直接合并','Same kind + tier: merge'],secondBody:['把新炮拖到已有炮上，松手就升阶。','Drop the new cannon onto the matching one.'],
mergeTitle:['叠在一起，合成一台','Drop one onto the other'],mergeBody:['两台同种同阶，合并后腾出空格。','Match kind and tier to merge and free space.'],
expandTitle:['合成成功！再扩一排','Merged! Add a board row'],expandBody:['点击扩板，为横着的磁轨炮留位置。','Add a row for the longer rail cannon.'],
railTitle:['长炮占横向三格','The rail needs three cells'],railBody:['拖进下面的亮框。它能贯穿一列敌人。','Drop it on the lit row. It pierces a line of enemies.'],
readyTitle:['挑选装置，准备守夜','Choose your next machine'],readyBody:['齿轮有限：买新炮，或刷新找同类合成。','Spend gears on new machines or reroll for a match.'],
waveTitle:['守住箱子，装置自动攻击','Protect the parts box'],waveBody:['漏怪会扣血。可以移动装置调整射程。','Escapes hurt the box. Move machines to adjust range.'],
fusionTitle:['3 阶弹簧＋3 阶磁轨','Tier 3 Spring + Tier 3 Rail'],fusionBody:['合为爆裂轨道炮，保留弹簧与磁轨强化。','Fuse into a Blast Rail. Keeps Spring and Rail upgrades.'],affectsFusion:['作用于 {n} 台（含融合炮）','Affects {n}, including Blast Rails'],
fusedTitle:['新发明：穿透后爆炸','An explosive invention'],fusedBody:['把备用炮放下，开始试射。','Place the spare cannon, then start the trial.'],
labwaveTitle:['看贯穿与爆炸的配合','Watch the piercing blast'],labwaveBody:['这是独立配方实验，不消耗本局资源。','A separate recipe trial, with free test materials.'],
tray:['待放置','READY TO PLACE'],trayHelp:['拖到空格，或直接合并同阶','Drop on empty cells or a matching tier'],empty:['装置已上阵','All deployed'],
shop:['备战席','BENCH'],price:['{n} 齿轮','{n} gears'],refresh:['换一批武器 · 5 齿轮','New batch · 5 gears'],soldOut:['已取走','Taken'],placeFirst:['先完成当前操作。','Complete the current action first.'],
noCoins:['齿轮不够，下一波结束会补给 5 个。','Not enough gears. Survive a wave to earn 5.'],
occupied:['底座被挡住了，请换完整的空位。','The base is blocked. Find enough empty cells.'],
differentRank:['{from}阶和{to}阶不能合，要两个同阶。','Tier {from} cannot merge with tier {to}. Match tiers.'],maxRank:['已到最高 4 阶，不能继续合并。','Tier 4 is the maximum.'],differentKind:['普通合并需要同种同阶。','A normal merge needs the same kind and tier.'],
outside:['整个底座都要放进工作板。','The whole base must fit on the board.'],choose:['先点选一台装置。','Select a machine first.'],ended:['本局已结束。','This run has ended.'],
placeOk:['装置就位','Machine deployed'],mergeOk:['升至 {n} 阶','Upgraded to tier {n}'],freed:[' · 腾出 {n} 格',' · Freed {n} cells'],fusionOk:['新配方完成','New invention assembled'],expandOk:['工作板新增 4 格','Four more cells unlocked'],leakOk:['敌人突破！箱子受损','An enemy escaped! Box damaged'],reward:['守住了！补给 +5 齿轮','Wave cleared! +5 gears'],
expandButton:['增加一排','Add a row'],start:['开始战斗','Start battle'],trial:['试射新发明','Test the invention'],waiting:['先完成眼前的拼装','Complete this assembly first'],observing:['装置正在攻击','Machines are firing'],speed:['速度 {n}×','Speed {n}×'],
patrol:['巡逻兵','Patrol'],runner:['快跑群','Runners'],swarm:['密集群','Swarm'],armor:['重甲队','Armored'],boss:['发条首领','Clockwork boss'],
patrolTip:['先买炮补强；普通漏怪扣 20 血。','Buy more firepower. Each escape costs 20 health.'],runnerTip:['速度更快，注意覆盖路线末端。','Faster enemies: cover the final stretch.'],swarmTip:['敌人扎堆，爆炸和穿透更有效。','Packed enemies favor blast and pierce.'],armorTip:['重甲减伤 35%，爆炸可以破甲。','Armor blocks 35%. Blasts ignore armor.'],bossTip:['首领突破扣 40 血，别只顾小兵。','The boss costs 40 health if it escapes.'],
next:['下一波 · {name}','Next · {name}'],waveReward:['已守住 {n} 波 · 补给已到账','{n} waves cleared · Supplies received'],
selected:['{name} · 射程 {n}','{name} · Range {n}'],cancelSelection:['取消选中','Deselect'],sell:['拆回 {n} 齿轮','Scrap · +{n}'],sellTitle:['拆回这台装置？','Scrap this machine?'],sellBody:['会返还 {n} 齿轮，装置从工作板移除。','Recover {n} gears and remove it from the board.'],
pause:['暂停','Pause'],paused:['工坊休息中','Taking a break'],pauseBody:['本局已暂停。刷新页面会重开，没有充值。','Run paused. Reload resets progress. No purchases with real money.'],
resume:['继续守夜','Resume'],restart:['重走教学','Replay tutorial'],newRun:['直接挑战 8 波','Play all 8 waves'],confirm:['确定','Confirm'],cancel:['取消','Cancel'],resetBody:['重新开始本次试玩？当前阵容会清空。','Restart this playtest? Your current build will be cleared.'],
soundOn:['声音已开','Sound on'],soundOff:['声音已关','Sound off'],language:['EN','中文'],hint:['重看手指提示','Show the hand again'],local:['测试版 · 刷新重开 · 无充值','Playtest · Reload resets · No payments'],
winTitle:['这一夜，守住了','The workshop is safe'],winBody:['8 波挑战完成。换一种采购与合成路线，再试一次？','All 8 waves survived. Try another build and buying route?'],
loseTitle:['零件箱失守了','The parts box was lost'],loseBody:['看看漏怪发生在哪一波。试着补群攻、调整射程或重新合成。','Check where enemies escaped. Try more area damage, range coverage, or merging.'],
labendTitle:['新发明，运转成功','Your invention works'],labendBody:['特殊配方改变攻击方式。回到整局试试你的组合。','The recipe changes your attack pattern. Try building it in a full run.'],
kept:['箱子剩余 {hp} 生命','{hp} box health left'],result:['击倒 {kills} · 漏过 {leaks}','{kills} defeated · {leaks} escaped'],passed:["通过 {n} / {total} 波","Cleared {n} / {total} waves"],toLab:['试试特殊配方','Try a fusion recipe'],
source:['按住','Hold'],target:['放这里','Drop here'],loadingError:['画布无法启动，请换浏览器重试。','Canvas could not start. Please try another browser.'],
};
export let locale=new URLSearchParams(location.search).get('lang')==='en'?'en':new URLSearchParams(location.search).get('lang')==='zh'?'zh':navigator.language.startsWith('zh')?'zh':'en';
export function toggleLocale(){locale=locale==='zh'?'en':'zh';}
export function t(key,vars={}){let s=copy[key]?.[locale==='zh'?0:1]||key;for(const[k,v]of Object.entries(vars))s=s.replaceAll('{'+k+'}',String(v));return s;}
